import { z } from "zod";

export const 
FoodItemSchema = z.object({
  item: z.string(),
  reason: z.string(),
  relatedCondition: z.string().optional(),
});

export const NutritionPlanSchema = z.object({
  summary: z
    .string()
    .describe("2-3 sentence overview of the patient's nutritional priorities"),
  foodsToAvoid: z.array(FoodItemSchema),
  nutrientsToLimit: z.array(FoodItemSchema),
  foodsToEat: z.array(FoodItemSchema),
  nutrientsToIncrease: z.array(FoodItemSchema),
  healthTips: z.array(z.string()),
  disclaimer: z
    .string()
    .default(
      "This is general nutrition information generated by AI, not medical advice. Consult a registered dietitian or your physician before changing your diet."
    ),
});

export type NutritionPlan = z.infer<typeof NutritionPlanSchema>;
