export function DisclaimerBanner() {
  return (
    <div className="disclaimer-banner" role="alert">
      <span className="disclaimer-icon" aria-hidden="true">
        ℹ️
      </span>
      <p>
        This tool provides general nutrition information generated by AI. It
        is not medical advice. Always consult a registered dietitian or your
        physician before changing your diet.
      </p>
    </div>
  );
}
