export function DisclaimerBanner() {
  return (
    <div className="disclaimer-banner" role="alert">
      This tool provides general nutrition information generated by AI. It is
      not medical advice. Always consult a registered dietitian or your
      physician before changing your diet.
    </div>
  );
}
